# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d795ec7c932c93b04cd96d5be7e2ed2fe49c63f7be245f6bc168efeeadacc99995e94e9cfaa78ed84762e9540454d4a06cd1bafb2fd373817e466215d684fd

test:
  secret_key_base: 642bb0aa7876814d4747cc3fcdb6f621a64be52350ef70f0738857706d29f4ce769ed833cffef1f6e52ae48529ae12adb611efec151a6cb405358a121a8f4f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
